apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: wl-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wl-deployment
  minReplicas: 1
  maxReplicas: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 25
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
    scaleUp: 
      stabilizationWindowSeconds: 5
